#!/usr/bin/env bash
# Optimized two-GPU full-quality Arabic Span-DTW training launcher.
set -euo pipefail

if [[ "$#" -ne 0 ]]; then
  echo "Usage: bash scripts/train/run_span_d3tw_optimized.sh" >&2
  echo "Override settings through environment variables." >&2
  exit 2
fi

SCRIPT_PATH="$(readlink -f "${BASH_SOURCE[0]}")"
if [[ -n "${PROJECT_DIR:-}" ]]; then
  PROJECT_DIR="$(readlink -f "${PROJECT_DIR}")"
else
  PROJECT_DIR="$(cd "$(dirname "${SCRIPT_PATH}")/../.." && pwd)"
fi
cd "${PROJECT_DIR}"
mkdir -p out logs logs/performance

set -a
CONDA_ENV="${CONDA_ENV:-manucripts_align}"
NUM_GPUS="${NUM_GPUS:-2}"
GPU_RESOURCE="${GPU_RESOURCE:-rtx_4090}"
PARTITION="${PARTITION:-rtx4090}"
CPUS_PER_TASK="${CPUS_PER_TASK:-$((8 * NUM_GPUS))}"
MEMORY="${MEMORY:-96G}"
TIME_LIMIT="${TIME_LIMIT:-07-00:00:00}"
SLURM_JOB_NAME="${SLURM_JOB_NAME:-align_opt}"
MAIL_USER="${MAIL_USER:-ahmedmas@post.bgu.ac.il}"

DATASET_TYPE="${DATASET_TYPE:-synthetic}"
LANGUAGE="${LANGUAGE:-Arabic}"
NUM_SAMPLES="${NUM_SAMPLES:-8000}"
DATASET_SPLIT_SEED="${DATASET_SPLIT_SEED:-42}"
TRAIN_SEED="${TRAIN_SEED:-42}"
if [[ -z "${DATA_DIR:-}" ]]; then
  if [[ -d "${PROJECT_DIR}/DataSet/Synthetic_Arabic_${NUM_SAMPLES}" ]]; then
    DATA_DIR="${PROJECT_DIR}/DataSet/Synthetic_Arabic_${NUM_SAMPLES}"
  elif [[ "${DATASET_TYPE}" == "real" ]]; then
    DATA_DIR="${PROJECT_DIR}/DataSet/ArabicDataset"
  else
    DATA_DIR="${PROJECT_DIR}/DataSet/Synthetic_Arabic"
  fi
fi

# Authoritative span semantics.
TEXT_ENCODER_TYPE="${TEXT_ENCODER_TYPE:-arabic_span}"
ARABIC_TEXT_MODEL_NAME="${ARABIC_TEXT_MODEL_NAME:-aubmindlab/bert-base-arabertv02}"
WINDOW_SIZE="${WINDOW_SIZE:-32}"
STRIDE_RATIO="${STRIDE_RATIO:-0.5}"
WINDOW_OVERLAP_MODE="${WINDOW_OVERLAP_MODE:-custom}"
VECTOR_SIZE="${VECTOR_SIZE:-128}"
USE_BILSTM="${USE_BILSTM:-1}"
BILSTM_LAYERS="${BILSTM_LAYERS:-2}"
USE_LOCAL_WINDOW_GROUPING="${USE_LOCAL_WINDOW_GROUPING:-1}"
LOCAL_GROUP_SIZE="${LOCAL_GROUP_SIZE:-3}"
MAX_TEXT_TOKEN_CHARS="${MAX_TEXT_TOKEN_CHARS:-2}"
MAX_TEXT_SPAN_CHARS="${MAX_TEXT_SPAN_CHARS:-2}"
MAX_WINDOWS_PER_SPAN="${MAX_WINDOWS_PER_SPAN:-3}"
SPAN_MAX_CORE_CHARS_CAP="${SPAN_MAX_CORE_CHARS_CAP:-2}"
SPAN_BOUNDARY_CONTEXT_CHARS="${SPAN_BOUNDARY_CONTEXT_CHARS:-1}"
SPAN_BOUNDARY_CONTEXT_MAX_CORE_CHARS="${SPAN_BOUNDARY_CONTEXT_MAX_CORE_CHARS:-1}"
SPAN_INCLUDE_SPACE_CONTEXT="${SPAN_INCLUDE_SPACE_CONTEXT:-0}"
SPAN_ALLOW_CHARACTER_SPACE_SURFACES="${SPAN_ALLOW_CHARACTER_SPACE_SURFACES:-0}"
SPAN_SPACE_TOKEN="${SPAN_SPACE_TOKEN:-<SPACE>}"
SPAN_SPACE_MAX_WINDOWS="${SPAN_SPACE_MAX_WINDOWS:-2}"
SPAN_EXTRA_WINDOWS_PER_CORE="${SPAN_EXTRA_WINDOWS_PER_CORE:-1}"
SPAN_USE_BLANK_TRANSITIONS="${SPAN_USE_BLANK_TRANSITIONS:-1}"
SPAN_BLANK_PENALTY="${SPAN_BLANK_PENALTY:-0.35}"
STRIP_SPAN_TEXT_EDGES="${STRIP_SPAN_TEXT_EDGES:-1}"

# Batched text/JAX path.
SPAN_DTW_BACKEND="${SPAN_DTW_BACKEND:-jax}"
SPAN_DTW_BUCKET_TEXT_LENGTHS="${SPAN_DTW_BUCKET_TEXT_LENGTHS:-1}"
SPAN_DTW_TEXT_BUCKET_SIZE="${SPAN_DTW_TEXT_BUCKET_SIZE:-16}"
SPAN_DTW_MAX_TEXT_BUCKET="${SPAN_DTW_MAX_TEXT_BUCKET:-256}"
SPAN_FEATURE_CACHE_SIZE="${SPAN_FEATURE_CACHE_SIZE:-8192}"
SPAN_FEATURE_CACHE_DTYPE="${SPAN_FEATURE_CACHE_DTYPE:-float16}"
SPAN_BACKBONE_BATCH_SIZE="${SPAN_BACKBONE_BATCH_SIZE:-512}"
CLEAR_SPAN_CACHE_EACH_EPOCH="${CLEAR_SPAN_CACHE_EACH_EPOCH:-0}"
CLEAR_FROZEN_SPAN_CACHE="${CLEAR_FROZEN_SPAN_CACHE:-0}"
JAX_COMPILATION_CACHE_DIR="${JAX_COMPILATION_CACHE_DIR:-${PROJECT_DIR}/.jax_cache}"
XLA_PYTHON_CLIENT_PREALLOCATE="${XLA_PYTHON_CLIENT_PREALLOCATE:-false}"

# Batch and objectives.
BATCH_SIZE="${BATCH_SIZE:-32}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-2}"
NUM_NEGATIVES="${NUM_NEGATIVES:-4}"
SPAN_DTW_ACTIVE_NEGATIVES_PER_SAMPLE="${SPAN_DTW_ACTIVE_NEGATIVES_PER_SAMPLE:-4}"
SPAN_NEGATIVE_GRAD_MODE="${SPAN_NEGATIVE_GRAD_MODE:-hardest}"
NEGATIVE_MODE="${NEGATIVE_MODE:-mixed}"
CONTRASTIVE_SOFT_DTW_GAMMA="${CONTRASTIVE_SOFT_DTW_GAMMA:-0.1}"
CONTRASTIVE_MARGIN="${CONTRASTIVE_MARGIN:-10.0}"
CONTRASTIVE_TEMPERATURE="${CONTRASTIVE_TEMPERATURE:-0.07}"
SPAN_WINDOW_COUNT_PENALTY="${SPAN_WINDOW_COUNT_PENALTY:-0.05}"
IMAGE_TEXT_LOSS_ON_BOTH_LINES="${IMAGE_TEXT_LOSS_ON_BOTH_LINES:-1}"

INK_CONTRAST_THRESHOLD="${INK_CONTRAST_THRESHOLD:-0.15}"
USE_LOCAL_HARD_NEGATIVES="${USE_LOCAL_HARD_NEGATIVES:-1}"
LOCAL_HARD_NEGATIVE_WEIGHT="${LOCAL_HARD_NEGATIVE_WEIGHT:-0.25}"
LOCAL_HARD_NEGATIVE_MARGIN="${LOCAL_HARD_NEGATIVE_MARGIN:-0.35}"
LOCAL_HARD_NEGATIVE_TOP_K="${LOCAL_HARD_NEGATIVE_TOP_K:-12}"
LOCAL_HARD_NEGATIVE_EXCLUDE_RADIUS="${LOCAL_HARD_NEGATIVE_EXCLUDE_RADIUS:-3}"
LOCAL_HARD_NEGATIVE_MIN_INK="${LOCAL_HARD_NEGATIVE_MIN_INK:-0.01}"
LOCAL_HARD_NEGATIVE_EVERY_N_BATCHES="${LOCAL_HARD_NEGATIVE_EVERY_N_BATCHES:-2}"
LOCAL_HARD_NEGATIVE_MAX_SAMPLES_PER_BATCH="${LOCAL_HARD_NEGATIVE_MAX_SAMPLES_PER_BATCH:-8}"

USE_IMAGE_PAIR_CONTRASTIVE="${USE_IMAGE_PAIR_CONTRASTIVE:-1}"
IMAGE_PAIR_LOSS_WEIGHT="${IMAGE_PAIR_LOSS_WEIGHT:-0.40}"
IMAGE_PAIR_MARGIN="${IMAGE_PAIR_MARGIN:-0.40}"
IMAGE_PAIR_TOP_K="${IMAGE_PAIR_TOP_K:-8}"
IMAGE_PAIR_EVERY_N_BATCHES="${IMAGE_PAIR_EVERY_N_BATCHES:-1}"
IMAGE_PAIR_MAX_SAMPLES_PER_BATCH="${IMAGE_PAIR_MAX_SAMPLES_PER_BATCH:-8}"
PAIR_COMPOSITION_MAX_REGIONS="${PAIR_COMPOSITION_MAX_REGIONS:-2}"
PAIR_COMPOSITION_MAX_CHARS="${PAIR_COMPOSITION_MAX_CHARS:-3}"
SEQUENCE_CONSISTENCY_LOSS_WEIGHT="${SEQUENCE_CONSISTENCY_LOSS_WEIGHT:-0.05}"
IMAGE_VARIANCE_LOSS_WEIGHT="${IMAGE_VARIANCE_LOSS_WEIGHT:-0.01}"
IMAGE_VARIANCE_TARGET_STD="${IMAGE_VARIANCE_TARGET_STD:-0.05}"

# Runtime optimizations.
OPTIMIZATION_MODE="${OPTIMIZATION_MODE:-quality}"
CNN_CHUNK_SIZE="${CNN_CHUNK_SIZE:-1024}"
USE_CHANNELS_LAST="${USE_CHANNELS_LAST:-1}"
ALLOW_TF32="${ALLOW_TF32:-1}"
CUDNN_BENCHMARK="${CUDNN_BENCHMARK:-1}"
FLOAT32_MATMUL_PRECISION="${FLOAT32_MATMUL_PRECISION:-high}"
USE_FUSED_ADAM="${USE_FUSED_ADAM:-1}"
TORCH_COMPILE_VISUAL="${TORCH_COMPILE_VISUAL:-0}"
DDP_STATIC_GRAPH="${DDP_STATIC_GRAPH:-1}"
USE_AMP="${USE_AMP:-1}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-2}"
ALLOW_JAX_DATALOADER_WORKERS="${ALLOW_JAX_DATALOADER_WORKERS:-1}"
DATALOADER_PREFETCH="${DATALOADER_PREFETCH:-2}"
DATALOADER_MP_CONTEXT="${DATALOADER_MP_CONTEXT:-spawn}"
PRELOAD_TRANSCRIPTS="${PRELOAD_TRANSCRIPTS:-1}"
STAGE_DATASET_TO_SCRATCH="${STAGE_DATASET_TO_SCRATCH:-1}"

# Schedule/output.
EPOCHS="${EPOCHS:-35}"
LEARNING_RATE="${LEARNING_RATE:-1e-4}"
VALID_EVERY_N_EPOCHS="${VALID_EVERY_N_EPOCHS:-2}"
VALID_MAX_BATCHES="${VALID_MAX_BATCHES:-20}"
FULL_CHECKPOINT_EVERY_N_EPOCHS="${FULL_CHECKPOINT_EVERY_N_EPOCHS:-5}"
MODEL_WEIGHTS_EVERY_N_EPOCHS="${MODEL_WEIGHTS_EVERY_N_EPOCHS:-2}"
LOG_MEMORY_EVERY_N_BATCHES="${LOG_MEMORY_EVERY_N_BATCHES:-25}"
PROFILE_TRAINING="${PROFILE_TRAINING:-0}"
PROFILE_MAX_BATCHES="${PROFILE_MAX_BATCHES:-0}"
ENABLE_NVTX="${ENABLE_NVTX:-0}"
USE_WANDB="${USE_WANDB:-1}"
WANDB_MODE="${WANDB_MODE:-online}"
WANDB_PROJECT="${WANDB_PROJECT:-alignment-project}"
JOB_ID="${JOB_ID:-${DATASET_TYPE}_arabic_optimized_${NUM_SAMPLES}_gpu${NUM_GPUS}}"
PRETRAINED_WEIGHTS="${PRETRAINED_WEIGHTS:-}"
RESUME="${RESUME:-}"

OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
MKL_NUM_THREADS="${MKL_NUM_THREADS:-4}"
TOKENIZERS_PARALLELISM="${TOKENIZERS_PARALLELISM:-false}"
PYTHONUNBUFFERED="${PYTHONUNBUFFERED:-1}"
NCCL_ASYNC_ERROR_HANDLING="${NCCL_ASYNC_ERROR_HANDLING:-1}"
NCCL_P2P_DISABLE="${NCCL_P2P_DISABLE:-1}"
NCCL_SHM_DISABLE="${NCCL_SHM_DISABLE:-0}"
HF_HUB_OFFLINE="${HF_HUB_OFFLINE:-1}"
TRANSFORMERS_OFFLINE="${TRANSFORMERS_OFFLINE:-1}"
set +a

if [[ -z "${SLURM_JOB_ID:-}" ]]; then
  echo "Submitting optimized training"
  echo "  branch checkout must contain scripts/train/train_optimized.py"
  echo "  dataset=${DATA_DIR} samples=${NUM_SAMPLES}"
  echo "  GPUs=${NUM_GPUS} microbatch/GPU=${BATCH_SIZE} accumulation=${GRADIENT_ACCUMULATION_STEPS}"
  echo "  effective global batch=$((BATCH_SIZE * NUM_GPUS * GRADIENT_ACCUMULATION_STEPS))"
  sbatch \
    --job-name="${SLURM_JOB_NAME}" \
    --output="${PROJECT_DIR}/out/%x_%J.out" \
    --chdir="${PROJECT_DIR}" \
    --partition="${PARTITION}" \
    --gpus="${GPU_RESOURCE}:${NUM_GPUS}" \
    --tasks=1 \
    --cpus-per-task="${CPUS_PER_TASK}" \
    --mem="${MEMORY}" \
    --time="${TIME_LIMIT}" \
    --mail-type=ALL \
    --mail-user="${MAIL_USER}" \
    --export=ALL,PROJECT_DIR="${PROJECT_DIR}" \
    "${SCRIPT_PATH}"
  exit 0
fi

source "$(conda info --base)/etc/profile.d/conda.sh"
conda activate "${CONDA_ENV}"
mkdir -p "${JAX_COMPILATION_CACHE_DIR}"

if [[ "${STAGE_DATASET_TO_SCRATCH}" == "1" && -n "${SLURM_SCRATCH_DIR:-}" ]]; then
  STAGED_DATA_DIR="${SLURM_SCRATCH_DIR}/$(basename "${DATA_DIR}")"
  mkdir -p "${STAGED_DATA_DIR}"
  echo "Staging dataset to ${STAGED_DATA_DIR}"
  if command -v rsync >/dev/null 2>&1; then
    rsync -a --delete "${DATA_DIR}/" "${STAGED_DATA_DIR}/"
  else
    cp -a "${DATA_DIR}/." "${STAGED_DATA_DIR}/"
  fi
  DATA_DIR="${STAGED_DATA_DIR}"
  export DATA_DIR
fi

if [[ -n "${PRETRAINED_WEIGHTS}" && -n "${RESUME}" ]]; then
  echo "ERROR: set PRETRAINED_WEIGHTS or RESUME, not both" >&2
  exit 1
fi
EXTRA_ARGS=()
if [[ -n "${PRETRAINED_WEIGHTS}" ]]; then
  [[ -f "${PRETRAINED_WEIGHTS}" ]] || { echo "ERROR: missing ${PRETRAINED_WEIGHTS}" >&2; exit 1; }
  EXTRA_ARGS+=(--pretrained_weights "${PRETRAINED_WEIGHTS}")
elif [[ -n "${RESUME}" ]]; then
  [[ -f "${RESUME}" ]] || { echo "ERROR: missing ${RESUME}" >&2; exit 1; }
  EXTRA_ARGS+=(--resume "${RESUME}")
fi

TRAIN_ARGS=(
  scripts/train/train_optimized.py
  --job_id "${JOB_ID}"
  --dataset_type "${DATASET_TYPE}"
  --data_dir "${DATA_DIR}"
  --num_samples "${NUM_SAMPLES}"
  --epochs "${EPOCHS}"
  --learning_rate "${LEARNING_RATE}"
  --negative_mode "${NEGATIVE_MODE}"
  --num_negatives "${NUM_NEGATIVES}"
  "${EXTRA_ARGS[@]}"
)
if [[ "${DATASET_TYPE}" == "real" ]]; then
  TRAIN_ARGS+=(--augment)
else
  TRAIN_ARGS+=(--no-augment)
fi

echo "Starting optimized training on $(hostname)"
echo "  data=${DATA_DIR}"
echo "  microbatch/GPU=${BATCH_SIZE}"
echo "  effective global batch=$((BATCH_SIZE * NUM_GPUS * GRADIENT_ACCUMULATION_STEPS))"
echo "  job=${JOB_ID}"
nvidia-smi -L || true

if (( NUM_GPUS > 1 )); then
  exec torchrun \
    --standalone \
    --nnodes=1 \
    --nproc_per_node="${NUM_GPUS}" \
    --max_restarts=0 \
    "${TRAIN_ARGS[@]}"
else
  exec python "${TRAIN_ARGS[@]}"
fi
