#!/usr/bin/env bash
# Clean ablation: latest direct sequence ranking + partial-overlap train positives.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Match the direct sequence-ranking pilot exactly except for the train mixture.
export AUGMENT="${AUGMENT:-0}"
export REAL_TRAIN_SAMPLES_PER_EPOCH="${REAL_TRAIN_SAMPLES_PER_EPOCH:-6000}"
export REAL_USE_EXTRA_NO_SHARED="${REAL_USE_EXTRA_NO_SHARED:-1}"
export REAL_EXTRA_EXCLUDE_EVAL_PAGES="${REAL_EXTRA_EXCLUDE_EVAL_PAGES:-1}"

export NO_SHARED_IMAGE_OBJECTIVE="sequence_ranking_partial_overlap"
export USE_SEQUENCE_ALIGNMENT_RANKING="${USE_SEQUENCE_ALIGNMENT_RANKING:-1}"
export SEQUENCE_RANKING_WEIGHT="${SEQUENCE_RANKING_WEIGHT:-0.10}"

export SEQUENCE_RANKING_THRESHOLD="${SEQUENCE_RANKING_THRESHOLD:-0.65}"
export SEQUENCE_RANKING_GAP="${SEQUENCE_RANKING_GAP:--0.30}"
export SEQUENCE_RANKING_TEMPERATURE="${SEQUENCE_RANKING_TEMPERATURE:-0.03}"

export SEQUENCE_RANKING_PATH_MARGIN="${SEQUENCE_RANKING_PATH_MARGIN:-0.03}"
export SEQUENCE_RANKING_SCORE_MARGIN="${SEQUENCE_RANKING_SCORE_MARGIN:-0.25}"
export SEQUENCE_RANKING_POSITIVE_FRACTION_FLOOR="${SEQUENCE_RANKING_POSITIVE_FRACTION_FLOOR:-0.15}"
export SEQUENCE_RANKING_PATH_COMPONENT_WEIGHT="${SEQUENCE_RANKING_PATH_COMPONENT_WEIGHT:-1.0}"
export SEQUENCE_RANKING_SCORE_COMPONENT_WEIGHT="${SEQUENCE_RANKING_SCORE_COMPONENT_WEIGHT:-0.20}"
export SEQUENCE_RANKING_POSITIVE_FLOOR_WEIGHT="${SEQUENCE_RANKING_POSITIVE_FLOOR_WEIGHT:-0.50}"
export SEQUENCE_RANKING_MAX_POS_SAMPLES_PER_BATCH="${SEQUENCE_RANKING_MAX_POS_SAMPLES_PER_BATCH:-4}"
export SEQUENCE_RANKING_MAX_NEG_SAMPLES_PER_BATCH="${SEQUENCE_RANKING_MAX_NEG_SAMPLES_PER_BATCH:-4}"

# Partial-overlap generator defaults. Override from the command line for ablations.
export REAL_PARTIAL_OVERLAP_MAX_SHARED_ISLANDS="${REAL_PARTIAL_OVERLAP_MAX_SHARED_ISLANDS:-3}"
export REAL_PARTIAL_OVERLAP_MULTI_ISLAND_PROB="${REAL_PARTIAL_OVERLAP_MULTI_ISLAND_PROB:-0.65}"
export REAL_PARTIAL_OVERLAP_THREE_ISLAND_PROB="${REAL_PARTIAL_OVERLAP_THREE_ISLAND_PROB:-0.15}"
export REAL_PARTIAL_OVERLAP_EDGE_DISTRACTOR_PROB="${REAL_PARTIAL_OVERLAP_EDGE_DISTRACTOR_PROB:-0.45}"
export REAL_PARTIAL_OVERLAP_MAX_TEXT_CHARS="${REAL_PARTIAL_OVERLAP_MAX_TEXT_CHARS:-150}"

# Keep text-side negatives identical to the sequence-ranking pilot.
export NUM_NEGATIVES="${NUM_NEGATIVES:-10}"
export SPAN_DTW_ACTIVE_NEGATIVES_PER_SAMPLE="${SPAN_DTW_ACTIVE_NEGATIVES_PER_SAMPLE:-4}"

exec bash "${SCRIPT_DIR}/run_real_finetune.sh"
