#!/usr/bin/env bash
# Pilot: direct local sequence-alignment ranking against no_shared_content.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

# Start from the healthy augmented-real Phase-3 representation and adapt only
# on the original real distribution.
export AUGMENT="${AUGMENT:-0}"
export REAL_TRAIN_SAMPLES_PER_EPOCH="${REAL_TRAIN_SAMPLES_PER_EPOCH:-6000}"
export REAL_USE_EXTRA_NO_SHARED="${REAL_USE_EXTRA_NO_SHARED:-1}"
export REAL_EXTRA_EXCLUDE_EVAL_PAGES="${REAL_EXTRA_EXCLUDE_EVAL_PAGES:-1}"

export NO_SHARED_IMAGE_OBJECTIVE="sequence_ranking"
export USE_SEQUENCE_ALIGNMENT_RANKING="${USE_SEQUENCE_ALIGNMENT_RANKING:-1}"
export SEQUENCE_RANKING_WEIGHT="${SEQUENCE_RANKING_WEIGHT:-0.10}"

# Match the best Phase-3 SW operating region found by the fixed diagnostic sweep.
export SEQUENCE_RANKING_THRESHOLD="${SEQUENCE_RANKING_THRESHOLD:-0.65}"
export SEQUENCE_RANKING_GAP="${SEQUENCE_RANKING_GAP:--0.30}"
export SEQUENCE_RANKING_TEMPERATURE="${SEQUENCE_RANKING_TEMPERATURE:-0.03}"

# Pairwise margins act on every positive x no-shared comparison in the batch.
export SEQUENCE_RANKING_PATH_MARGIN="${SEQUENCE_RANKING_PATH_MARGIN:-0.03}"
export SEQUENCE_RANKING_SCORE_MARGIN="${SEQUENCE_RANKING_SCORE_MARGIN:-0.25}"
export SEQUENCE_RANKING_POSITIVE_FRACTION_FLOOR="${SEQUENCE_RANKING_POSITIVE_FRACTION_FLOOR:-0.15}"
export SEQUENCE_RANKING_PATH_COMPONENT_WEIGHT="${SEQUENCE_RANKING_PATH_COMPONENT_WEIGHT:-1.0}"
export SEQUENCE_RANKING_SCORE_COMPONENT_WEIGHT="${SEQUENCE_RANKING_SCORE_COMPONENT_WEIGHT:-0.20}"
export SEQUENCE_RANKING_POSITIVE_FLOOR_WEIGHT="${SEQUENCE_RANKING_POSITIVE_FLOOR_WEIGHT:-0.50}"
export SEQUENCE_RANKING_MAX_POS_SAMPLES_PER_BATCH="${SEQUENCE_RANKING_MAX_POS_SAMPLES_PER_BATCH:-4}"
export SEQUENCE_RANKING_MAX_NEG_SAMPLES_PER_BATCH="${SEQUENCE_RANKING_MAX_NEG_SAMPLES_PER_BATCH:-4}"

# Keep the established text-side negative recipe unchanged for a clean ablation.
export NUM_NEGATIVES="${NUM_NEGATIVES:-10}"
export SPAN_DTW_ACTIVE_NEGATIVES_PER_SAMPLE="${SPAN_DTW_ACTIVE_NEGATIVES_PER_SAMPLE:-4}"

exec bash "${SCRIPT_DIR}/run_real_finetune.sh"
