#!/usr/bin/env bash
# New optimization run. Never initialize from a previous full-model checkpoint.
set -euo pipefail
PROJECT_DIR="${PROJECT_DIR:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
cd "$PROJECT_DIR"
export ARCHITECTURE_VARIANT=resnet18_128d_5l_1h_no_pos
export MODEL_BACKEND_VARIANT=resnet_token
export JOB_NAME="${JOB_NAME:-resnet18_128d_5l_1h_no_pos_$(date +%Y%m%d_%H%M%S)}"
export EPOCH_MONITORING=1
export LOCAL_DROPOUT="${LOCAL_DROPOUT:-0.10}"
export TINY_VIT_DROPOUT="${TINY_VIT_DROPOUT:-0.0}"
export FUSION_DROPOUT=0
export RESTORATION_EPOCHS="${RESTORATION_EPOCHS:-30}"
export RESTORATION_LEARNING_RATE="${RESTORATION_LEARNING_RATE:-2e-5}"
export RESTORATION_NUM_SAMPLES=0
export REAL_TRAIN_SAMPLES_PER_EPOCH="${REAL_TRAIN_SAMPLES_PER_EPOCH:-0}"
export REAL_TRAIN_AUGMENT_COPIES="${REAL_TRAIN_AUGMENT_COPIES:-3}"
export DATASET_TYPE=real REAL_SYNTHETIC_STYLE=0 REAL_BINARIZE=0
export REAL_BINARIZE_AUTO_INVERT=0 REAL_BINARIZE_AUTOCONTRAST=0 REAL_AUGMENT=0
export VISUAL_INPUT_CHANNELS=1 VISUAL_GRAYSCALE=1 REAL_GRAYSCALE=1
export REAL_BBOX_CROP=1 REAL_BBOX_CROP_STRICT=1
export REAL_BBOX_MARGIN_RATIO="${REAL_BBOX_MARGIN_RATIO:-0.05}"
export REAL_BBOX_MIN_MARGIN_PX="${REAL_BBOX_MIN_MARGIN_PX:-2}"
export ZERO_SHOT_FOREGROUND_CROP=0 ZERO_SHOT_PRESERVE_ASPECT=0
export ZERO_SHOT_SOURCE_GEOMETRY=0 ZERO_SHOT_PREPROCESS=1
export ZERO_SHOT_CROP_MODE=vertical_borders LINE_GEOMETRY_MODE=xml-bbox-gray-full-resize
export PACK_VALID_WINDOWS=0 FULL_IMAGE_NO_PADDING=1
export REAL_MANIFEST_NAME=dataset_manifest_full_pairs.jsonl
export REAL_INDEPENDENT_LINES=1 REAL_ALL_PAGE_LINES=1 REAL_DATASET_LABELS=all
export REAL_TEXT_KEY="${REAL_TEXT_KEY:-text_original_path}"
export REAL_MIN_TEXT_SCORE=0.0 REAL_SPLIT_BY_PAIR_ID=1 REAL_FILTER_INFEASIBLE_SPAN_DTW=0
export REAL_SCAN_AUGMENT=1
export REAL_SCAN_AUGMENT_PROB="${REAL_SCAN_AUGMENT_PROB:-0.95}"
export REAL_SCAN_BRIGHTNESS_DELTA="${REAL_SCAN_BRIGHTNESS_DELTA:-0.12}"
export REAL_SCAN_CONTRAST_DELTA="${REAL_SCAN_CONTRAST_DELTA:-0.22}"
export REAL_SCAN_BLUR_PROB="${REAL_SCAN_BLUR_PROB:-0.55}"
export REAL_SCAN_BLUR_RADIUS_MIN="${REAL_SCAN_BLUR_RADIUS_MIN:-0.35}"
export REAL_SCAN_BLUR_RADIUS_MAX="${REAL_SCAN_BLUR_RADIUS_MAX:-1.40}"
export REAL_SCAN_GAUSSIAN_NOISE_PROB="${REAL_SCAN_GAUSSIAN_NOISE_PROB:-0.75}"
export REAL_SCAN_GAUSSIAN_NOISE_STD_MIN="${REAL_SCAN_GAUSSIAN_NOISE_STD_MIN:-5.0}"
export REAL_SCAN_GAUSSIAN_NOISE_STD_MAX="${REAL_SCAN_GAUSSIAN_NOISE_STD_MAX:-16.0}"
export REAL_SCAN_SPECKLE_PROB="${REAL_SCAN_SPECKLE_PROB:-0.30}"
export REAL_SCAN_SPECKLE_FRACTION="${REAL_SCAN_SPECKLE_FRACTION:-0.0010}"
export RESTORATION_NUM_NEGATIVES="${RESTORATION_NUM_NEGATIVES:-0}"
export RESTORATION_CONTRASTIVE_WEIGHT="${RESTORATION_CONTRASTIVE_WEIGHT:-0.0}"
export RESTORATION_DTW_STRIDE_RATIO="${RESTORATION_DTW_STRIDE_RATIO:-0.50}"
export POSITIVE_LETTER_DTW_WEIGHT="${POSITIVE_LETTER_DTW_WEIGHT:-1.0}"
export POSITIVE_LETTER_DTW_GAMMA_START="${POSITIVE_LETTER_DTW_GAMMA_START:-0.05}"
export POSITIVE_LETTER_DTW_GAMMA_END="${POSITIVE_LETTER_DTW_GAMMA_END:-0.05}"
export POSITIVE_LETTER_DTW_ANNEAL_EPOCHS="${POSITIVE_LETTER_DTW_ANNEAL_EPOCHS:-1}"
export POSITIVE_LETTER_DTW_VERTICAL_PENALTY="${POSITIVE_LETTER_DTW_VERTICAL_PENALTY:-0.05}"
export POSITIVE_LETTER_DTW_HORIZONTAL_PENALTY="${POSITIVE_LETTER_DTW_HORIZONTAL_PENALTY:-0.30}"
export POSITIVE_LETTER_DTW_POSITION_PRIOR="${POSITIVE_LETTER_DTW_POSITION_PRIOR:-0.15}"
export POSITIVE_LETTER_DTW_DISABLE_HORIZONTAL_WHEN_FEASIBLE=1
export POSITIVE_LETTER_DTW_COMPETITION_TEMPERATURE="${POSITIVE_LETTER_DTW_COMPETITION_TEMPERATURE:-0.10}"
export POSITIVE_LETTER_DTW_COST_MODE="${POSITIVE_LETTER_DTW_COST_MODE:-full_alphabet_nll}"
export LETTER_CODEBOOK_SEED="${LETTER_CODEBOOK_SEED:-1234}"
export SIGREG_LAMBDA="${SIGREG_LAMBDA:-0.20}"
export SIGREG_SKETCH_DIM="${SIGREG_SKETCH_DIM:-1024}"
export SIGREG_NUM_KNOTS="${SIGREG_NUM_KNOTS:-17}"
export SIGREG_T_MIN="${SIGREG_T_MIN:-0.0}" SIGREG_T_MAX="${SIGREG_T_MAX:-3.0}"
export SIGREG_MIN_SAMPLES="${SIGREG_MIN_SAMPLES:-32}" SIGREG_SLICE_CHUNK="${SIGREG_SLICE_CHUNK:-128}"
export TORCH_HOME="${TORCH_HOME:-$PROJECT_DIR/Pretrained/torch}"
export RESNET18_PRETRAINED=1 TINY_VIT_PRETRAINED=0 PRETRAINED_LOCAL_ONLY=1
export HF_HUB_OFFLINE=1 TRANSFORMERS_OFFLINE=1
export AMP_DTYPE="${AMP_DTYPE:-bf16}" OMP_NUM_THREADS="${OMP_NUM_THREADS:-4}"
export TRAIN_SAMPLE_EVAL=0
export PYTHONPATH="$PROJECT_DIR:${PYTHONPATH:-}"
PYTHON_BIN="${PYTHON_BIN:-python}"
if [[ "${NPROC:-1}" == 1 ]]; then
    exec "$PYTHON_BIN" train.py --dataset "${DATASET:-DataSet/ArabicDataset}" "$@"
else
    exec "$PYTHON_BIN" -m torch.distributed.run --standalone --nproc_per_node="$NPROC" train.py --dataset "${DATASET:-DataSet/ArabicDataset}" "$@"
fi
